
CondaError: Run 'conda init' before 'conda activate'

/home/miaozl/miniconda3/envs/moco/lib/python3.8/site-packages/MinkowskiEngine-0.5.4-py3.8-linux-x86_64.egg/MinkowskiEngine/__init__.py:36: UserWarning: The environment variable `OMP_NUM_THREADS` not set. MinkowskiEngine will automatically set `OMP_NUM_THREADS=16`. If you want to set `OMP_NUM_THREADS` manually, please export it on the command line before running a python script. e.g. `export OMP_NUM_THREADS=12; python your_program.py`. It is recommended to set it below 24.
  warnings.warn(
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
/home/miaozl/miniconda3/envs/moco/lib/python3.8/site-packages/pytorch_lightning/trainer/configuration_validator.py:74: You defined a `validation_step` but have no `val_dataloader`. Skipping val loop.
You are using a CUDA device ('NVIDIA GeForce RTX 4090') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/1
----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All distributed processes registered. Starting with 1 processes
----------------------------------------------------------------------------------------------------

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name                  | Type                  | Params
----------------------------------------------------------------
0 | encoder               | MOSModel              | 28.3 M
1 | ClassificationMetrics | ClassificationMetrics | 0     
2 | loss                  | NLLLoss               | 0     
----------------------------------------------------------------
28.3 M    Trainable params
0         Non-trainable params
28.3 M    Total params
113.146   Total estimated model params size (MB)
SLURM auto-requeueing enabled. Setting signal handlers.
/home/miaozl/miniconda3/envs/moco/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/logger_connector/result.py:441: It is recommended to use `self.log('epoch_sta_iou', ..., sync_dist=True)` when logging on epoch level in distributed setting to accumulate the metric across devices.
/home/miaozl/miniconda3/envs/moco/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/logger_connector/result.py:441: It is recommended to use `self.log('epoch_mov_iou', ..., sync_dist=True)` when logging on epoch level in distributed setting to accumulate the metric across devices.
Epoch 9, global step 12310: 'epoch' reached 9.00000 (best 9.00000), saving model to './logs/mos_baseline/mos4d_shuffle/20%nuscenes/vs-0.1_t-3.0_bs-4/version_1/checkpoints/epoch=9.ckpt' as top 400
Epoch 19, global step 24620: 'epoch' reached 19.00000 (best 19.00000), saving model to './logs/mos_baseline/mos4d_shuffle/20%nuscenes/vs-0.1_t-3.0_bs-4/version_1/checkpoints/epoch=19.ckpt' as top 400
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/home/miaozl/miniconda3/envs/moco/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/miaozl/miniconda3/envs/moco/lib/python3.8/site-packages/tensorboard/summary/writer/event_file_writer.py", line 244, in run
    self._run()
  File "/home/miaozl/miniconda3/envs/moco/lib/python3.8/site-packages/tensorboard/summary/writer/event_file_writer.py", line 275, in _run
    self._record_writer.write(data)
  File "/home/miaozl/miniconda3/envs/moco/lib/python3.8/site-packages/tensorboard/summary/writer/record_writer.py", line 40, in write
    self._writer.write(header + header_crc + data + footer_crc)
  File "/home/miaozl/miniconda3/envs/moco/lib/python3.8/site-packages/tensorboard/compat/tensorflow_stub/io/gfile.py", line 773, in write
    self.fs.append(self.filename, file_content, self.binary_mode)
  File "/home/miaozl/miniconda3/envs/moco/lib/python3.8/site-packages/tensorboard/compat/tensorflow_stub/io/gfile.py", line 167, in append
    self._write(filename, file_content, "ab" if binary_mode else "a")
  File "/home/miaozl/miniconda3/envs/moco/lib/python3.8/site-packages/tensorboard/compat/tensorflow_stub/io/gfile.py", line 171, in _write
    with io.open(filename, mode, encoding=encoding) as f:
FileNotFoundError: [Errno 2] No such file or directory: b'./logs/mos_baseline/mos4d_shuffle/20%nuscenes/vs-0.1_t-3.0_bs-4/version_1/events.out.tfevents.1736044907.MaRS-GPU-server.1113520.0'
[rank0]: Traceback (most recent call last):
[rank0]:   File "mos4d_baseline_script.py", line 404, in <module>
[rank0]:     mos4d_baseline_train(cfg[args.mode], dataset_cfg, args.resume_version)
[rank0]:   File "mos4d_baseline_script.py", line 105, in mos4d_baseline_train
[rank0]:     trainer.fit(model, train_dataloader)
[rank0]:   File "/home/miaozl/miniconda3/envs/moco/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 544, in fit
[rank0]:     call._call_and_handle_interrupt(
[rank0]:   File "/home/miaozl/miniconda3/envs/moco/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 67, in _call_and_handle_interrupt
[rank0]:     logger.finalize("failed")
[rank0]:   File "/home/miaozl/miniconda3/envs/moco/lib/python3.8/site-packages/lightning_utilities/core/rank_zero.py", line 42, in wrapped_fn
[rank0]:     return fn(*args, **kwargs)
[rank0]:   File "/home/miaozl/miniconda3/envs/moco/lib/python3.8/site-packages/pytorch_lightning/loggers/tensorboard.py", line 226, in finalize
[rank0]:     super().finalize(status)
[rank0]:   File "/home/miaozl/miniconda3/envs/moco/lib/python3.8/site-packages/lightning_utilities/core/rank_zero.py", line 42, in wrapped_fn
[rank0]:     return fn(*args, **kwargs)
[rank0]:   File "/home/miaozl/miniconda3/envs/moco/lib/python3.8/site-packages/lightning_fabric/loggers/tensorboard.py", line 299, in finalize
[rank0]:     self.experiment.flush()
[rank0]:   File "/home/miaozl/miniconda3/envs/moco/lib/python3.8/site-packages/torch/utils/tensorboard/writer.py", line 1256, in flush
[rank0]:     writer.flush()
[rank0]:   File "/home/miaozl/miniconda3/envs/moco/lib/python3.8/site-packages/torch/utils/tensorboard/writer.py", line 152, in flush
[rank0]:     self.event_writer.flush()
[rank0]:   File "/home/miaozl/miniconda3/envs/moco/lib/python3.8/site-packages/tensorboard/summary/writer/event_file_writer.py", line 125, in flush
[rank0]:     self._async_writer.flush()
[rank0]:   File "/home/miaozl/miniconda3/envs/moco/lib/python3.8/site-packages/tensorboard/summary/writer/event_file_writer.py", line 186, in flush
[rank0]:     self._check_worker_status()
[rank0]:   File "/home/miaozl/miniconda3/envs/moco/lib/python3.8/site-packages/tensorboard/summary/writer/event_file_writer.py", line 212, in _check_worker_status
[rank0]:     raise exception
[rank0]:   File "/home/miaozl/miniconda3/envs/moco/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 43, in _call_and_handle_interrupt
[rank0]:     return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
[rank0]:   File "/home/miaozl/miniconda3/envs/moco/lib/python3.8/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 105, in launch
[rank0]:     return function(*args, **kwargs)
[rank0]:   File "/home/miaozl/miniconda3/envs/moco/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 580, in _fit_impl
[rank0]:     self._run(model, ckpt_path=ckpt_path)
[rank0]:   File "/home/miaozl/miniconda3/envs/moco/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 987, in _run
[rank0]:     results = self._run_stage()
[rank0]:   File "/home/miaozl/miniconda3/envs/moco/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1033, in _run_stage
[rank0]:     self.fit_loop.run()
[rank0]:   File "/home/miaozl/miniconda3/envs/moco/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 205, in run
[rank0]:     self.advance()
[rank0]:   File "/home/miaozl/miniconda3/envs/moco/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 363, in advance
[rank0]:     self.epoch_loop.run(self._data_fetcher)
[rank0]:   File "/home/miaozl/miniconda3/envs/moco/lib/python3.8/site-packages/pytorch_lightning/loops/training_epoch_loop.py", line 140, in run
[rank0]:     self.advance(data_fetcher)
[rank0]:   File "/home/miaozl/miniconda3/envs/moco/lib/python3.8/site-packages/pytorch_lightning/loops/training_epoch_loop.py", line 278, in advance
[rank0]:     trainer._logger_connector.update_train_step_metrics()
[rank0]:   File "/home/miaozl/miniconda3/envs/moco/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/logger_connector/logger_connector.py", line 163, in update_train_step_metrics
[rank0]:     self.log_metrics(self.metrics["log"])
[rank0]:   File "/home/miaozl/miniconda3/envs/moco/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/logger_connector/logger_connector.py", line 118, in log_metrics
[rank0]:     logger.save()
[rank0]:   File "/home/miaozl/miniconda3/envs/moco/lib/python3.8/site-packages/lightning_utilities/core/rank_zero.py", line 42, in wrapped_fn
[rank0]:     return fn(*args, **kwargs)
[rank0]:   File "/home/miaozl/miniconda3/envs/moco/lib/python3.8/site-packages/pytorch_lightning/loggers/tensorboard.py", line 213, in save
[rank0]:     super().save()
[rank0]:   File "/home/miaozl/miniconda3/envs/moco/lib/python3.8/site-packages/lightning_utilities/core/rank_zero.py", line 42, in wrapped_fn
[rank0]:     return fn(*args, **kwargs)
[rank0]:   File "/home/miaozl/miniconda3/envs/moco/lib/python3.8/site-packages/lightning_fabric/loggers/tensorboard.py", line 293, in save
[rank0]:     self.experiment.flush()
[rank0]:   File "/home/miaozl/miniconda3/envs/moco/lib/python3.8/site-packages/torch/utils/tensorboard/writer.py", line 1256, in flush
[rank0]:     writer.flush()
[rank0]:   File "/home/miaozl/miniconda3/envs/moco/lib/python3.8/site-packages/torch/utils/tensorboard/writer.py", line 152, in flush
[rank0]:     self.event_writer.flush()
[rank0]:   File "/home/miaozl/miniconda3/envs/moco/lib/python3.8/site-packages/tensorboard/summary/writer/event_file_writer.py", line 125, in flush
[rank0]:     self._async_writer.flush()
[rank0]:   File "/home/miaozl/miniconda3/envs/moco/lib/python3.8/site-packages/tensorboard/summary/writer/event_file_writer.py", line 194, in flush
[rank0]:     self._check_worker_status()
[rank0]:   File "/home/miaozl/miniconda3/envs/moco/lib/python3.8/site-packages/tensorboard/summary/writer/event_file_writer.py", line 212, in _check_worker_status
[rank0]:     raise exception
[rank0]:   File "/home/miaozl/miniconda3/envs/moco/lib/python3.8/threading.py", line 932, in _bootstrap_inner
[rank0]:     self.run()
[rank0]:   File "/home/miaozl/miniconda3/envs/moco/lib/python3.8/site-packages/tensorboard/summary/writer/event_file_writer.py", line 244, in run
[rank0]:     self._run()
[rank0]:   File "/home/miaozl/miniconda3/envs/moco/lib/python3.8/site-packages/tensorboard/summary/writer/event_file_writer.py", line 275, in _run
[rank0]:     self._record_writer.write(data)
[rank0]:   File "/home/miaozl/miniconda3/envs/moco/lib/python3.8/site-packages/tensorboard/summary/writer/record_writer.py", line 40, in write
[rank0]:     self._writer.write(header + header_crc + data + footer_crc)
[rank0]:   File "/home/miaozl/miniconda3/envs/moco/lib/python3.8/site-packages/tensorboard/compat/tensorflow_stub/io/gfile.py", line 773, in write
[rank0]:     self.fs.append(self.filename, file_content, self.binary_mode)
[rank0]:   File "/home/miaozl/miniconda3/envs/moco/lib/python3.8/site-packages/tensorboard/compat/tensorflow_stub/io/gfile.py", line 167, in append
[rank0]:     self._write(filename, file_content, "ab" if binary_mode else "a")
[rank0]:   File "/home/miaozl/miniconda3/envs/moco/lib/python3.8/site-packages/tensorboard/compat/tensorflow_stub/io/gfile.py", line 171, in _write
[rank0]:     with io.open(filename, mode, encoding=encoding) as f:
[rank0]: FileNotFoundError: [Errno 2] No such file or directory: b'./logs/mos_baseline/mos4d_shuffle/20%nuscenes/vs-0.1_t-3.0_bs-4/version_1/events.out.tfevents.1736044907.MaRS-GPU-server.1113520.0'
mv: cannot stat 'train_20.292': No such file or directory
